name: go_router_poc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.4.1
  build_runner: ^2.4.8
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
